services:    
    restfulsubversion_repocache_db:
        class: PDO
        arguments: [%repocache_db%]
        public: false

    restfulsubversion_repocache:
        class: RestfulSubversion\Core\RepoCache
        arguments: [@restfulsubversion_repocache_db]
        public: false

    restfulsubversion_changeset_transformer:
        class: MyHammer\RestfulSubversionBundle\Transformer\ChangesetTransformer
        public: false

    restfulsubversion_changeset_repository:
        class: MyHammer\RestfulSubversionBundle\Entity\ChangesetRepository
        arguments: [@restfulsubversion_repocache, @restfulsubversion_changeset_transformer]
        public: true

    restfulsubversion_repofile_transformer:
        class: MyHammer\RestfulSubversionBundle\Transformer\RepoFileTransformer
        public: false

    restfulsubversion_repofile_repository:
        class: MyHammer\RestfulSubversionBundle\Entity\ChangesetRepository
        arguments: [@restfulsubversion_repocache, @restfulsubversion_repofile_transformer]
        public: true
